version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminder_bot
    env_file: .env
    volumes:
      - ./reminder_bot/data/remind_base.db:/src/remind_base.db:rw
    restart: unless-stopped