[project]
name = "reminder_bot"
version = "0.1.0"
requires-python = ">=3.10"
description = "nothing yet"
authors = [{ name = "Damir"}]
license = "MIT"
readme = "README.md"

dependencies = [
    "aiogram==3.21.0",
    "aiosqlite==0.21.0",
    "asyncpg==0.30.0",
    "colorlog==6.9.0",
    "python-dotenv==1.1.1",
    "SQLAlchemy==2.0.41",
    "tzdata==2025.2",
    "dateparser==1.2.2",
]
